version: "3.4"
services:
  user-service:
    build:
      context: .
      target: developer
    ports:
      - "5000:5000"
    environment:
        - FLASKAPP=app.py
        - SECRET=fishsauce
  
    volumes:
        - ./:/app
