POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "username": "testuser1",
    "password": "testpassword",
    "email": "testemail@gmail.com"
 }

###
POST http://localhost:5000/login/ HTTP/1.1
content-type: application/json

{
    "username": "testuser1",
    "password": "testpassword"
 }

###


GET http://localhost:5000/user
?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NidJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsImVtYWlsIjoidGVzdGVtYWlsQGdtYWlsLmNvbSIsImlkIjo1MTUsInRpbWUiOiJcIjIwMjAtMTEtMjQgMTQ6NTg6MzkuMzkwNTEzXCIifQ.LmlFMWcL4a64ft9ZHQkpCDQ-Sn6kMMK5EW7M28SL18A

###